ProyectoSegurosFpDaw/Controllers/AccesoController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ProyectoSegurosFpDaw.BLL;
using ProyectoSegurosFpDaw.Models;
using ProyectoSegurosFpDaw.Persistance;

namespace ProyectoSegurosFpDaw.Controllers
{
    [RequireHttps]
    public class AccesoController : Controller
    {
        private ProyectoSegurosDbEntities context;
        private UnitOfWork unitOfWork;
        private AccesoBLL accessoBLL; 
        
        public AccesoController() 
        {
            context = new ProyectoSegurosDbEntities();
            unitOfWork = new UnitOfWork(context);
            accessoBLL = new AccesoBLL(unitOfWork);            
        }
        

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string User, string Pass)
        {            
            try
            {                
                var unitOfWork = new UnitOfWork(context);                
                var usuarioAutenticado = accessoBLL.GetAuthenticatedUsuario(User, Pass);

                if (usuarioAutenticado == null)
                {
                    ViewBag.Error = "Usuario o contraseña inválida";
                    return View();
                }
                
                Session["User"] = usuarioAutenticado;
                Session.Timeout = 25;
               
                return RedirectToAction("Index", "GestionPolizas");
            }
            catch (Exception)
            {
                ViewBag.Error = "Error inesperado al intentar autenticar al usuario";
                return View();
            }
        }
        
        [HttpGet]
        public ActionResult LoginOut()
        {
            Session["user"] = null;
            Session.Abandon();
            return RedirectToAction("Login");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoSegurosFpDaw/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using ProyectoSegurosFpDaw.BLL;
using ProyectoSegurosFpDaw.Filtros;
using ProyectoSegurosFpDaw.Models;
using ProyectoSegurosFpDaw.Persistance;

namespace ProyectoSegurosFpDaw.Controllers
{
    [RequireHttps]
    public class ClientesController : Controller
    {
        private ProyectoSegurosDbEntities context;
        private UnitOfWork unitOfWork;
        private ClienteBLL clienteBll;

        public ClientesController()
        {
            context = new ProyectoSegurosDbEntities();
            unitOfWork = new UnitOfWork(context);
            clienteBll = new ClienteBLL(unitOfWork);
        }
        #region Actions

        /// <summary>
        /// GET : muestra formulario para buscar clientes y listado con los resultados.
        /// </summary>
        /// <returns>Vista con formulario y resultados.</returns>
        [AutorizarUsuario(permisoId: 10)]
        [HttpGet]
        public ActionResult Index()
        {
            // Estadosession que se envía a la vista a través de ViewBag
            // para colapsar/mostrar la sección que corresponda.
            // 1=>Buscar Cliente
            // 2=>Resultados            
            var estadoSession = "1";

            // Comprueba que haya mensajes enviado desde otra action.
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.mensaje = TempData["mensaje"];
            }

            // Recupera lista de clientes coincidentes si viene de la acción BuscarClientes.
            if (TempData.ContainsKey("clientesCoincidentes"))
            {
                estadoSession = "2";
                var clientesCoincidentes = TempData["clientesCoincidentes"];
                ViewBag.clientesCoincidentes = clientesCoincidentes;
            }
            ViewBag.estadoSession = estadoSession;
            return View();
        }

        [AutorizarUsuario(permisoId: 19)]
        [HttpGet]
        public ActionResult BuscarClientes(string clienteId, string dniCliente, string emailCliente, string telefonoCliente)
        {
            try
            {
                ClienteSearchingFields searchingField = clienteBll.GetSearchingField(clienteId, dniCliente, emailCliente, telefonoCliente);
                List<Cliente> clienteMatches = clienteBll.SearchClientes(searchingField);

                if (clienteMatches.Any() && clienteMatches.FirstOrDefault().activo == 0)
                {
                    var clienteNoActivo = clienteMatches.FirstOrDefault();
                    TempData["mensaje"] = ItemMensaje.ErrorBuscarRegistroEliminado(Usuario.GetNombreModelo(), clienteNoActivo.clienteId);
                }
                TempData["clientesCoincidentes"] = clienteMatches;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["mensaje"] = ItemMensaje.ErrorExcepcionBuscar(Cliente.GetNombreModelo(), ex.GetType().ToString());
                return RedirectToAction("Index");
            }          
        }


        [AutorizarUsuario(permisoId: 9)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.mensaje = TempData["mensaje"];
            }

            Cliente cliente = unitOfWork.Cliente.SingleOrDefault(c => c.clienteId == id);
            if (cliente == null)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosDetails(Cliente.GetNombreModelo());
                return RedirectToAction("Index");
            }
            if (cliente.activo == 0)
            {
                TempData["mensaje"] = ItemMensaje.ErrorBuscarRegistroEliminado(Cliente.GetNombreModelo(), cliente.clienteId);
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        [AutorizarUsuario(permisoId: 6)]
        [HttpGet]
        public ActionResult Create()
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.mensaje = TempData["mensaje"];
            }
            return View();
        }

        [AutorizarUsuario(permisoId: 6)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "nombreCliente,apellido1Cliente,apellido2Cliente,dniCliente,emailCliente,telefonoCliente")] Cliente cliente)
        {
            if (ModelState.IsValid == false || clienteBll.FieldsFormat(cliente) == false)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosCrear(Cliente.GetNombreModelo());
                return RedirectToAction("Index");

            }
            if (clienteBll.AnyClienteWithDni(cliente.dniCliente))
            {
                ViewBag.mensaje = ItemMensaje.ErrorRegistroDuplicadoCrear(Cliente.GetNombreModelo(), "NIF/NIE", null);
                return View(cliente);
            }
            try
            {
                clienteBll.CreateNewCliente(cliente);
                TempData["mensaje"] = ItemMensaje.SuccessCrear(Cliente.GetNombreModelo(), cliente.dniCliente);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = ItemMensaje.ErrorExcepcionCrear(Cliente.GetNombreModelo(), ex.GetType().ToString());
                return View(cliente);
            }

        }

        [AutorizarUsuario(permisoId: 7)]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Cliente cliente = unitOfWork.Cliente.GetClienteActivo(id);
            if (cliente == null)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosEditar(Cliente.GetNombreModelo());
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        [AutorizarUsuario(permisoId: 7)]
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int id)
        {

            Cliente cliente = unitOfWork.Cliente.GetClienteActivo(id);
            if (cliente == null)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosEditar(Cliente.GetNombreModelo());
                return RedirectToAction("Index");
            }
            if (TryUpdateModel(cliente, "", new string[] { "nombreCliente", "apellido1Cliente", "apellido2Cliente", "emailCliente", "telefonoCliente" }) == false)
            {
                ViewBag.mensaje = ItemMensaje.ErrorDatosNoValidosEditar(Cliente.GetNombreModelo());
                return View(cliente);
            }
            if (clienteBll.FieldsFormat(cliente) == false)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosEditar(Cliente.GetNombreModelo());
                return RedirectToAction("Index");
            }
            try
            {
                clienteBll.UpdateCliente();
                TempData["mensaje"] = ItemMensaje.SuccessEditar(Cliente.GetNombreModelo(), cliente.apellido1Cliente);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = ItemMensaje.ErrorExcepcionEditar(Cliente.GetNombreModelo(), ex.GetType().ToString());
                return View(cliente);
            }
        }

        /// <summary>
        /// POST: modifica cliente => activo = 0.
        ///  El cliente no se elimina en la BBDD
        /// para poder seguir consultando pólizas del cliente.
        /// </summary>
        /// <param name="clienteId">cliente Id</param>
        /// <return>
        /// Ok => Modifica registro en BBDD y redirecciona a Index con mensaje de success.
        /// Error => redirecciona a Index / Details con mensaje de error.
        /// </return>
        [AutorizarUsuario(permisoId: 8)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int clienteId)
        {
            Cliente cliente = unitOfWork.Cliente.GetClienteActivo(clienteId);
            if (cliente == null)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosDesactivar(Cliente.GetNombreModelo());
                return RedirectToAction("Index");
            }
            // Verifica que el cliente tenga pólizas en vigor.       
            var polizasVigor = context.Poliza.Where(c => c.clienteId == clienteId && c.activo == 1).Select(c => c.polizaId).ToList();
            if (polizasVigor.Any())
            {
                TempData["mensaje"] = ItemMensaje.ErrorPolizaVigorDesactivarCondicionado(Cliente.GetNombreModelo(), polizasVigor);
                return RedirectToAction("Details", new { id = cliente.clienteId });
            }
            else
            {
                try
                {
                    clienteBll.DeleteCliente(cliente);
                    TempData["mensaje"] = ItemMensaje.SuccessDesactivar(Cliente.GetNombreModelo(), cliente.apellido1Cliente);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["mensaje"] = ItemMensaje.ErrorExcepcionDesactivar(Cliente.GetNombreModelo(), ex.GetType().ToString());
                    return RedirectToAction("Index");
                }
            }
        }
        #endregion
        #region Métodos

        /// <summary>
        /// Comprueba a través de llamada Ajax desde la vista, 
        /// si el NIF / NIE introducido existe en Clientes.  
        /// </summary>
        /// <param name="dni">NIF/NIE cliente</param>
        /// <returns>
        /// Json : 
        /// 1 => hay coincidencia.

ProyectoSegurosFpDaw/Views/Shared/Error500.cshtml
@{
    ViewBag.Title = "Error";
}

<!-- Header -->
<section class="fixedHeader-locked">
    <div col-sm-3>
        <div class="card card-gray ">
            <div class="card-header">
                <h2 class="card-title">ERROR 500 Internal Server Error</h2>
            </div>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Error General</h3>
                    <div class="card-tools">
                    </div>
                </div>
                <div class="card-body">
                    <div class="error-page">
                        <p>Error interno del servidor</p>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</section>
<!-- /.content -->

ProyectoSegurosFpDaw/Views/Shared/_LayoutLogado.cshtml
<!DOCTYPE html>
<!-- PLANTILLA BASADA EN https://adminlte.io -->
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title / SegurosFicticios / Proyecto FP DAW</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/content/adminlte/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Sweet Alert  -->
    <link href="~/plugins/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/Content/SharedCSS.css" rel="stylesheet" />
    @RenderSection("css", required: false)
</head>
<body class="hold-transition sidebar-mini">

    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="@Url.Action("Index", "GestionPolizas")" class="brand-link">
                <i class="fas fa-car-crash"></i>
                <span class="brand-text font-weight-light ml-2"><b>Seguros</b>Ficticios</span>
            </a>
            <!-- Sidebar -->
            @{
                var usuarioActual = Session["User"] as ProyectoSegurosFpDaw.Models.Usuario;
                if (Session["user"] != null)
                {
                    var rolUsuarioActual = usuarioActual.rolId;
                    <div class="sidebar">
                        <!-- Sidebar user panel (optional) -->
                        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                            <div class="info col-9 mr-2">
                                <a href="@Url.Action("Details", "Usuarios", new { id = usuarioActual.usuarioId} )" title="Detalle Usuario">
                                    <i class="fas fa-user-circle mr-2"></i>
                                    @usuarioActual.nombreUsuario
                                    @usuarioActual.apellido1Usuario
                                </a>
                            </div>
                            <div class="info col-3 ">
                                <a href=" @Url.Action("loginOut", "Acceso")" title="Desconectar Sesión">
                                    <i class="fas fa-power-off"></i>
                                </a>
                            </div>
                        </div>
                        @if (rolUsuarioActual != 2)
                        {
                            <!-- Sidebar Menu -->
                            <nav class="mt-2">
                                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                                    <li class="nav-item has-treeview">
                                        <a href="#" class="nav-link">
                                            <i class="nav-icon fas fa-sun "></i>
                                            <p>
                                                Pólizas
                                                <i class="right fas fa-angle-left"></i>
                                            </p>
                                        </a>
                                        <ul class="nav nav-treeview">
                                            <li class="nav-item">
                                                <a href="@Url.Action("Index", "GestionPolizas")" class="nav-link">
                                                    <i class="fas fa-search-plus nav-icon"></i>
                                                    <p>Gestión Pólizas</p>
                                                </a>
                                            </li>
                                            @if (rolUsuarioActual == 4)
                                            {
                                                <li class="nav-item">
                                                    <a href="@Url.Action("IndexNoEditable", "CondicionadoPolizas")" class="nav-link">
                                                        <i class="fas fa-clipboard-list nav-icon"></i>
                                                        <p>Condicionados Póliza</p>
                                                    </a>
                                                </li>
                                            }
                                            else
                                            {
                                                <li class="nav-item">
                                                    <a href="@Url.Action("Index", "CondicionadoPolizas")" class="nav-link">
                                                        <i class="fas fa-clipboard-list nav-icon"></i>
                                                        <p>Condicionados Póliza</p>
                                                    </a>
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                    @if (rolUsuarioActual == 1 || rolUsuarioActual == 3)
                                    {
                                        <li class="nav-item">
                                            <a href="@Url.Action("Index", "RolesPermisos")" class="nav-link">
                                                <i class="fas fa-user-tag nav-icon"></i>
                                                <p>Roles</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="@Url.Action("Index", "Usuarios")" class="nav-link">
                                                <i class="fas fa-users nav-icon"></i>
                                                <p>Usuarios</p>
                                            </a>
                                        </li>
                                    }
                                    <li class="nav-item">
                                        <a href="@Url.Action("Index", "Clientes")" class="nav-link">
                                            <i class="fas fa-user-tie nav-icon"></i>
                                            <p>Clientes</p>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                            <!-- /.sidebar-menu -->
                        }
                    </div>
                }
            }
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right  d-sm-inline">
                <a href="@Url.Action("About", "Home")" class="link-black">
                    <strong>About</strong>
                </a>
            </div>
            <!-- Default to the left -->
            <a href="@Url.Action("About", "Home")" class="link-black">
                <strong>Proyecto Fin de Ciclo FP DAW Ilerna 2020</strong>
            </a>
        </footer>
    </div>
    <!-- ./wrapper -->


    @if (ViewBag.mensaje != null)
    {
        // Gestiona mensajes enviados desde el controller
        var mensaje = @ViewBag.mensaje as ProyectoSegurosFpDaw.Models.ItemMensaje;
        <span>
            @Html.Hidden("mensaje", mensaje.Mensaje.ToString())
            @Html.Hidden("tipo", mensaje.Tipo)
        </span>
    }

    <!-- Scripts / Librerías Js -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/content/adminlte/dist/js/adminlte.min.js"></script>
    <!-- Sweet Alert  -->
    <script src="~/plugins/sweetalert2/sweetalert2.all.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>