ProyectoSegurosFpDaw/Models/CondicionadoPoliza.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSegurosFpDaw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionadoPoliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CondicionadoPoliza()
        {
            this.GestionPoliza = new HashSet<GestionPoliza>();
        }
    
        public int condicionadoPolizaId { get; set; }
        public string tipoCondicionado { get; set; }
        public string garantias { get; set; }
        public int activo { get; set; }
        public Nullable<System.DateTime> fechaDesactivado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionPoliza> GestionPoliza { get; set; }
    }
}

ProyectoSegurosFpDaw/Controllers/CondicionadoPolizasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using ProyectoSegurosFpDaw.BLL;
using ProyectoSegurosFpDaw.Filtros;
using ProyectoSegurosFpDaw.Models;
using ProyectoSegurosFpDaw.Persistance;

namespace ProyectoSegurosFpDaw.Controllers
{
    [RequireHttps]
    public class CondicionadoPolizasController : Controller
    {
        private ProyectoSegurosDbEntities context;
        private UnitOfWork unitOfWork;
        private CondicionadoPolizaBLL condicionadoPolizaBLL;

        public CondicionadoPolizasController()
        {
            context = new ProyectoSegurosDbEntities();
            unitOfWork = new UnitOfWork(context);
            condicionadoPolizaBLL = new CondicionadoPolizaBLL(unitOfWork);
        }
        #region Actions

        [AutorizarUsuario(permisoId: 23)]
        [HttpGet]
        public ActionResult Index()
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.mensaje = TempData["mensaje"];
            }
            ViewBag.listaCondicionados = unitOfWork.CondicionadoPoliza.GetAll();

            return View();
        }

        [AutorizarUsuario(permisoId: 22)]
        [HttpGet]
        public ActionResult IndexNoEditable()
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.mensaje = TempData["mensaje"];
            }
            ViewBag.listaCondicionados = unitOfWork.CondicionadoPoliza.GetAll();

            return View();
        }

        [AutorizarUsuario(permisoId: 23)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "tipoCondicionado,garantias")] CondicionadoPoliza condicionadoPoliza)
        {
            if (ModelState.IsValid == false || condicionadoPolizaBLL.FieldsFormat(condicionadoPoliza) == false)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosCrear(CondicionadoPoliza.GetNombreModelo());
                return RedirectToAction("Index");
            }
            if (condicionadoPolizaBLL.AnyCondicionadoWithTipoCondicionado(condicionadoPoliza.tipoCondicionado))
            {
                TempData["mensaje"] = ItemMensaje.ErrorRegistroDuplicadoCrear(CondicionadoPoliza.GetNombreModelo(), "tipo de condicionado", null);
                return RedirectToAction("Index");
            }
            try
            {
                condicionadoPolizaBLL.CreateNewCondicionadoPoliza(condicionadoPoliza);
                TempData["mensaje"] = ItemMensaje.SuccessCrear(CondicionadoPoliza.GetNombreModelo(), condicionadoPoliza.tipoCondicionado);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["mensaje"] = ItemMensaje.ErrorExcepcionCrear(CondicionadoPoliza.GetNombreModelo(), ex.GetType().ToString());
                return RedirectToAction("Index");
            }
        }

        [AutorizarUsuario(permisoId: 23)]
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int IDcondicionado)
        {
            CondicionadoPoliza condicionadoPoliza = unitOfWork.CondicionadoPoliza.Get(IDcondicionado);
            string tipoCondicionadoAntiguo = condicionadoPoliza.tipoCondicionado;

            if (condicionadoPoliza == null || TryUpdateModel(condicionadoPoliza, "", new string[] { "tipoCondicionado", "garantias" }) == false)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosEditar(CondicionadoPoliza.GetNombreModelo());
                return RedirectToAction("Index");
            }
            if (condicionadoPolizaBLL.FieldsFormat(condicionadoPoliza) == false)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosEditar(CondicionadoPoliza.GetNombreModelo());
                return RedirectToAction("Index");
            }
            if (condicionadoPoliza.tipoCondicionado != tipoCondicionadoAntiguo
                && condicionadoPolizaBLL.AnyCondicionadoWithTipoCondicionado(condicionadoPoliza.tipoCondicionado))
            {
                TempData["mensaje"] = ItemMensaje.ErrorRegistroDuplicadoEditar(CondicionadoPoliza.GetNombreModelo(), "tipo de condicionado", null);
                return RedirectToAction("Index");
            }
            try
            {
                unitOfWork.CondicionadoPoliza.Update(condicionadoPoliza);
                unitOfWork.SaveChanges();
                TempData["mensaje"] = ItemMensaje.SuccessEditar(CondicionadoPoliza.GetNombreModelo(), condicionadoPoliza.tipoCondicionado);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["mensaje"] = ItemMensaje.ErrorExcepcionEditar(CondicionadoPoliza.GetNombreModelo(), ex.GetType().ToString());
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// POST : Activa y desactiva Condicionado Póliza (vigente / no vigente) 
        /// <para>Activo = 1 (vigente) / 
        /// Activo = 0 (no vigente).</para>
        /// </summary>        
        [AutorizarUsuario(permisoId: 23)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int condicionadoId)
        {
            CondicionadoPoliza condicionadoPoliza = unitOfWork.CondicionadoPoliza.Get(condicionadoId);
            if (condicionadoPoliza == null)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosDesactivarActivar(CondicionadoPoliza.GetNombreModelo());
                return RedirectToAction("Index");
            }
            
            if (condicionadoPoliza.activo == 1)
            {
                // Validación :  no se puede desactivar condicionado si alguna póliza en vigor (activa) tiene ese tipo de Condicionado.
                if (condicionadoPolizaBLL.AnyPolizaActivaWithThisCondicionado(condicionadoPoliza) == true)
                {
                    List<int> polizasIdActivas = condicionadoPolizaBLL.GetPolizasActivasIdWithThisCondicionado(condicionadoPoliza);
                    TempData["mensaje"] = ItemMensaje.ErrorPolizaVigorDesactivarCondicionado(CondicionadoPoliza.GetNombreModelo(), polizasIdActivas);
                    return RedirectToAction("Index");
                }
                try
                {
                    condicionadoPolizaBLL.DeleteCondicionado(condicionadoPoliza);
                    TempData["mensaje"] = ItemMensaje.SuccessDesactivar(CondicionadoPoliza.GetNombreModelo(), condicionadoPoliza.tipoCondicionado);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["mensaje"] = ItemMensaje.ErrorExcepcionDesactivar(CondicionadoPoliza.GetNombreModelo(), ex.GetType().ToString());
                    return RedirectToAction("Index");
                }
            }            
            if (condicionadoPoliza.activo == 0)
            {
                try
                {
                    condicionadoPolizaBLL.UnDeleteCondicionado(condicionadoPoliza);
                    TempData["mensaje"] = ItemMensaje.SuccessActivar(CondicionadoPoliza.GetNombreModelo(), condicionadoPoliza.tipoCondicionado);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["mensaje"] = ItemMensaje.ErrorExcepcionActivar(CondicionadoPoliza.GetNombreModelo(), ex.GetType().ToString());
                    return RedirectToAction("Index");
                }
            }
            TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosDesactivarActivar(CondicionadoPoliza.GetNombreModelo());
            return RedirectToAction("Index");
        }
        #endregion

        #region Métodos

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion

    }
}

ProyectoSegurosFpDaw/Views/CondicionadoPolizas/Index.cshtml
@model ProyectoSegurosFpDaw.Models.CondicionadoPoliza

@{
    ViewBag.Title = "Condicionados Póliza";
}

<!-- Header -->
<section class="fixedHeader-locked">
    <div col-sm-3>
        <div class="card card-gray ">
            <div class="card-header">
                <h2 class="card-title">CONDICIONADOS DE PÓLIZA</h2>
            </div>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        @if (ViewBag.listaCondicionados != null)
        {
            var listaCondicionados = ViewBag.listaCondicionados as IList<ProyectoSegurosFpDaw.Models.CondicionadoPoliza>;
            if (listaCondicionados.Count > 0)
            {
                foreach (var item in listaCondicionados)
                {
                    // Variables para cambiar iconos / title / vigente /colores de card
                    // y variar los id de cada card. 
                    string colorCard = "";
                    string vigente = "";
                    string nId = item.condicionadoPolizaId.ToString();
                    string numIdCondNav = "cond" + nId;
                    string numIdGarantNav = "garan" + nId;
                    string numIdCondContent = "condContent" + nId;
                    string numIdGarantContent = "garanContent" + nId;
                    string iconoBorrar = "";
                    string titleBorrar = "";
                    string titleVigente = "";

                    // Si condicionado está activo/no activo,
                    // muestra icono de Eliminar / Recuperar y modifica color.
                    if (item.activo == 1)
                    {
                        colorCard = "card-info";
                        iconoBorrar = "fa-trash-alt";
                        titleBorrar = "Eliminar Condicionado";
                        titleVigente = "";
                    }
                    else
                    {
                        colorCard = "card-gray";
                        vigente = "No vigente";
                        iconoBorrar = "fa-trash-restore-alt";
                        titleBorrar = "Recuperar Condicionado";
                        titleVigente = "Desde " + item.fechaDesactivado;
                    }
                    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4">
                        <div class="card @colorCard card-tabs">
                            <div class="card-header p-0 pt-1">
                                <ul class="nav nav-tabs" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="@numIdCondNav" data-toggle="pill" href="#@numIdCondContent" role="tab" aria-controls="@numIdCondContent" aria-selected="true" title="@titleVigente">Condicionado @vigente</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="@numIdGarantNav" data-toggle="pill" href="#@numIdGarantContent" role="tab" aria-controls="@numIdGarantContent" aria-selected="false">Garantías</a>
                                    </li>
                                    @if (item.activo == 1)
                                    {
                                        <li class="nav-item">
                                            <input type="hidden" name="IDcondicionado" value="@item.condicionadoPolizaId" />
                                            <button class="btn btn-outline-light nav-link btnEditar" title="Editar Condicionado">
                                                <i class="fas fa-pencil-alt"></i>
                                            </button>
                                        </li>
                                    }
                                    <li class="nav-item">
                                        @using (Html.BeginForm("Delete", "CondicionadoPolizas", FormMethod.Post, new { role = "form" }))
                                        {
                                            @Html.AntiForgeryToken()
                                            <input type="hidden" name="condicionadoId" value="@item.condicionadoPolizaId" />
                                            <button class="btn btn-outline-light nav-link btnEliminar" title="@titleBorrar">
                                                <i class="fas @iconoBorrar"></i>
                                            </button>
                                        }
                                    </li>
                                </ul>
                            </div>
                            @using (Html.BeginForm("Edit", "CondicionadoPolizas", FormMethod.Post, new { role = "form", id = nId }))
                            {
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="IDCondicionado" value="@item.condicionadoPolizaId" />
                                <div class="card-body">
                                    <div class="tab-content">
                                        <div class="tab-pane fade show active" id="@numIdCondContent" role="tabpanel" aria-labelledby="@numIdCondNav">
                                            @Html.TextBox("tipoCondicionado" + nId, item.tipoCondicionado, new { @class = "form-control", @readonly = true, maxlength = "50" })
                                            <input hidden name="tipoCondicionado"/>
                                        </div>
                                        <div class="tab-pane fade" id="@numIdGarantContent" role="tabpanel" aria-labelledby="@numIdGarantNav">
                                            @Html.TextArea("garantias" + nId, item.garantias, new { @class = "form-control", @readonly = true, maxlength = "500", rows = "1" })
                                            <input hidden name="garantias" />
                                        </div>
                                    </div>
                                </div>
                            }
                            <!-- /.card -->
                        </div>
                    </div>
                }
            }
        }
    </div>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4">
            <div class="card card-gray-dark card-tabs">
                <div class="card-header p-0 pt-1">
                    <ul class="nav nav-tabs" id="cardCrear" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="cardCrearTab" data-toggle="pill" href="#cardCrearHome" role="tab" aria-controls="cardCrearHome" aria-selected="true">Nuevo Condicionado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="crearGarantiasTab" data-toggle="pill" href="#garantiasTabContent" role="tab" aria-controls="garantiasTabContent" aria-selected="false">Garantías</a>
                        </li>
                        <li class="nav-item">
                            <button id="btnCrear" class="btn btn-outline-light nav-link" title="Crear Condicionado">
                                <i class="fas fa-save"></i>
                            </button>
                        </li>
                    </ul>
                </div>
                @using (Html.BeginForm("Create", "CondicionadoPolizas", FormMethod.Post, new { role = "form", id = "formCreate" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="card-body">
                        <div class="tab-content" id="cardCrearContent">
                            <div class="tab-pane fade show active" id="cardCrearHome" role="tabpanel" aria-labelledby="cardCrearTab">
                                @Html.EditorFor(model => model.tipoCondicionado, new { htmlAttributes = new { @class = "form-control", @placeholder = "nombre", maxlength = "50" } })
                            </div>
                            <div class="tab-pane fade" id="garantiasTabContent" role="tabpanel" aria-labelledby="crearGarantiasTab">
                                @Html.EditorFor(model => model.garantias, new { htmlAttributes = new { @class = "form-control", @placeholder = "GARANTÍAS ", maxlength = "500", rows = "1" } })
                            </div>
                        </div>
                    </div>
                }
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script src="~/Scripts/SharedScripts.js"></script>
    <script src="~/Scripts/CondicionadoPolizaSharedScripts.js"></script>
    <script src="~/Scripts/CondicionadoPolizaIndexScript.js"></script>
}

ProyectoSegurosFpDaw/Views/CondicionadoPolizas/IndexNoEditable.cshtml
@model ProyectoSegurosFpDaw.Models.CondicionadoPoliza

@{
    ViewBag.Title = "Condicionados Póliza";    
}

<!-- Header -->
<section class="fixedHeader-locked">
    <div col-sm-3>
        <div class="card card-gray ">
            <div class="card-header">
                <h2 class="card-title">CONDICIONADOS DE PÓLIZA</h2>
            </div>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        @if (ViewBag.listaCondicionados != null)
        {
            var listaCondicionados = ViewBag.listaCondicionados as IList<ProyectoSegurosFpDaw.Models.CondicionadoPoliza>;
            if (listaCondicionados.Count > 0)
            {
                foreach (var item in listaCondicionados)
                {
                    // Variables para cambiar iconos / title / vigente /colores de card
                    // y variar los id de cada card. 
                    string colorCard = "";
                    string vigente = "";
                    string nId = item.condicionadoPolizaId.ToString();
                    string numIdCondNav = "cond" + nId;
                    string numIdGarantNav = "garan" + nId;
                    string numIdCondContent = "condContent" + nId;
                    string numIdGarantContent = "garanContent" + nId;
                    string titleVigente = "";

                    if (item.activo == 1)
                    {
                        colorCard = "card-info";
                        titleVigente = ""; 
                    }
                    else
                    {
                        colorCard = "card-gray"; 
                        vigente = "No vigente";
                        titleVigente = "Desde " + item.fechaDesactivado;
                    }
                    <div class="col-12 col-sm-12 col-lg-4">
                        <div class="card @colorCard card-tabs">
                            <div class="card-header p-0 pt-1">
                                <ul class="nav nav-tabs" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="@numIdCondNav" data-toggle="pill" href="#@numIdCondContent" role="tab" aria-controls="@numIdCondContent" aria-selected="true" title="@titleVigente">Condicionado @vigente</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="@numIdGarantNav" data-toggle="pill" href="#@numIdGarantContent" role="tab" aria-controls="@numIdGarantContent" aria-selected="false">Garantías</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content">
                                    <div class="tab-pane fade show active" id="@numIdCondContent" role="tabpanel" aria-labelledby="@numIdCondNav">
                                        @Html.TextBox("tipoCondicionado" + nId, item.tipoCondicionado, new { @class = "form-control", @readonly = true, maxlength = "50" })
                                    </div>
                                    <div class="tab-pane fade" id="@numIdGarantContent" role="tabpanel" aria-labelledby="@numIdGarantNav">
                                        @Html.TextArea("garantias" + nId, item.garantias, new { @class = "form-control", @readonly = true, maxlength = "500", rows = "1" })
                                    </div>
                                </div>
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                }
            }
        }
    </div>
</section>