ProyectoSegurosFpDaw/Models/GestionPoliza.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSegurosFpDaw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionPoliza
    {
        public int gestionPolizaId { get; set; }
        public string matricula { get; set; }
        public string marcaVehiculo { get; set; }
        public string modeloVehiculo { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int precio { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fechaGestion { get; set; }
        public int condicionadoPolizaId { get; set; }
        public int tipoGestionId { get; set; }
        public int polizaId { get; set; }
        public int usuarioId { get; set; }
    
        public virtual CondicionadoPoliza CondicionadoPoliza { get; set; }
        public virtual Poliza Poliza { get; set; }
        public virtual TipoGestion TipoGestion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}

ProyectoSegurosFpDaw/Controllers/GestionPolizasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Web.WebPages;
using Microsoft.Ajax.Utilities;
using ProyectoSegurosFpDaw.BLL;
using ProyectoSegurosFpDaw.Controllers.Helpers;
using ProyectoSegurosFpDaw.Filtros;
using ProyectoSegurosFpDaw.Models;
using ProyectoSegurosFpDaw.Persistance;

namespace ProyectoSegurosFpDaw.Controllers
{
    [RequireHttps]
    public class GestionPolizasController : Controller
    {
        private ProyectoSegurosDbEntities context;
        private UnitOfWork unitOfWork;
        private GestionPolizaBLL gestionPolizaBLL;
        private GestionPolizasControllerHelper helper;
        public GestionPolizasController()
        {
            context = new ProyectoSegurosDbEntities();
            unitOfWork = new UnitOfWork(context);
            gestionPolizaBLL = new GestionPolizaBLL(unitOfWork);
            helper = new GestionPolizasControllerHelper();
        }

        #region Actions

        /// <summary>
        /// GET : muestra formulario para buscar Pólizas y listado con los resultados.
        /// </summary>
        /// <returns>Vista con formulario y resultados.</returns>    
        [AutorizarUsuario(permisoId: 16)]
        [HttpGet]
        public ActionResult Index()
        {

            // Estadosession que se envía a la vista a través de ViewBag
            // para colapsar/mostrar la sección que corresponda.
            // 1=>Buscar Póliza
            // 2=>Resultados          
            var estadoSession = "1";

            //Comprueba que haya mensajes enviado desde otra action 
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.mensaje = TempData["mensaje"];
            }

            // Recupera lista de pólizas coincidentes 
            // si viene de la acción BuscarPólizas.
            if (TempData.ContainsKey("polizasCoincidentes"))
            {
                estadoSession = "2";
                var polizasCoincidentes = TempData["polizasCoincidentes"];
                ViewBag.polizasCoincidentes = polizasCoincidentes;
            }

            // Select list con Estados de póliza
            // 0 => no vigente
            // 1 => vigente
            // 2 => todos
            ViewBag.estadoPoliza = helper.GetSelectListEstadoPolizaConOpcionTodos();
            ViewBag.estadoSession = estadoSession;
            return View();
        }

        /// <summary>
        /// GET : busca la última gestión de cada póliza que coincida con los parámetros introducidos.
        /// </summary> 
        [HttpGet]
        [AutorizarUsuario(permisoId: 20)]
        public ActionResult BuscarPolizas(int? polizaId, string matricula, string dniCliente, string telefonoCliente, string fechaInicio, string fechaFinal, string estadoPoliza)
        {
            if (gestionPolizaBLL.IsValidSearching(fechaInicio, fechaFinal, estadoPoliza) == false)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosBuscar(Poliza.GetNombreModelo());
                return RedirectToAction("Index");
            }

            try
            {
                PolizaSearchingFields searchingFields = gestionPolizaBLL.GetSearchingFields(polizaId, matricula, dniCliente, telefonoCliente, fechaInicio, fechaFinal, estadoPoliza);

                List<GestionPoliza> results = gestionPolizaBLL.SearchPolizas(searchingFields);

                TempData["polizasCoincidentes"] = results;
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                TempData["mensaje"] = ItemMensaje.ErrorExcepcionBuscar(Poliza.GetNombreModelo(), ex.GetType().ToString());
                return RedirectToAction("Index");
            }


        }

        [AutorizarUsuario(permisoId: 15)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            GestionPoliza gestionPoliza = unitOfWork.GestionPoliza.GetGestionPolizaWithClienteCondicionadoTipoGestion(id);
            if (gestionPoliza == null)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosDetails(Poliza.GetNombreModelo());
                return RedirectToAction("Index");
            }
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.mensaje = TempData["mensaje"];
            }
            return View(gestionPoliza);
        }


        [AutorizarUsuario(permisoId: 17)]
        [HttpGet]
        public ActionResult Historico(int id)
        {
            List<GestionPoliza> historicoPoliza = gestionPolizaBLL.GetHistoricoPoliza(id);
            if (historicoPoliza == null)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosBuscar(Poliza.GetNombreModelo());
                return RedirectToAction("Index");
            }
            ViewBag.historicoLista = historicoPoliza;
            ViewBag.polizaId = id;
            ViewBag.gestionPolizaIdLast = gestionPolizaBLL.GetLastGestionPoliza(id).gestionPolizaId;
            return View();
        }

        /// <summary>
        /// GET: formulario para crear una nueva póliza.
        /// </summary>
        /// <param name="clienteDni">NIF/NIE cliente</param>
        /// <returns>
        /// si ya existe el cliente => vista con formulario para crear póliza con datos del cliente.
        /// si no existe el cliente => Vista con formulario para crear cliente. 
        /// </returns>
        [AutorizarUsuario(permisoId: 12)]
        [HttpGet]
        public ActionResult Create(string clienteDni)
        {
            if (clienteDni.IsNullOrWhiteSpace())
            {
                TempData["mensaje"] = ItemMensaje.ErrorNifNoValidoCrearPoliza(Poliza.GetNombreModelo());
                return RedirectToAction("Index");
            }
            clienteDni = clienteDni.Trim().ToUpperInvariant();
            Cliente cliente = unitOfWork.Cliente.Where(c => c.dniCliente == clienteDni).FirstOrDefault();
            if (cliente == null)
            {
                TempData["mensaje"] = ItemMensaje.ErrorNifNoExisteCrearPoliza(Poliza.GetNombreModelo(), clienteDni);
                return RedirectToAction("Create", "Clientes");
            }
            if (cliente.activo == 0)
            {
                TempData["mensaje"] = ItemMensaje.ErrorBuscarRegistroEliminado(Cliente.GetNombreModelo(), cliente.clienteId);
                return RedirectToAction("Index");
            }
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.mensaje = TempData["mensaje"];
            }
            ViewBag.cliente = cliente;
            ViewBag.condicionadoPolizaId = new SelectList(unitOfWork.CondicionadoPoliza.Where(c => c.activo == 1), "condicionadoPolizaId", "tipoCondicionado");
            return View();
        }

        /// <summary>
        /// POST : crea una nueva póliza, y la primera gestionPoliza asociada a esa póliza.
        /// </summary>    
        [AutorizarUsuario(permisoId: 12)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "matricula,marcaVehiculo,modeloVehiculo,fechaInicio,fechaFin,precio,observaciones,condicionadoPolizaId")] GestionPoliza gestionPoliza, string clienteId)
        {
            if (ModelState.IsValid == false || gestionPolizaBLL.FieldsFormatCreate(gestionPoliza, clienteId) == false)
            {
                TempData["mensaje"] = ItemMensaje.ErrorDatosNoValidosCrear(Poliza.GetNombreModelo());
                return RedirectToAction("Index");
            }
            Cliente cliente = unitOfWork.Cliente.Get(int.Parse(clienteId));
            if (gestionPolizaBLL.ValidarFormatoMatricula(gestionPoliza.matricula) == false)
            {
                TempData["mensaje"] = ItemMensaje.ErrorValidarFormatoMatricula(Poliza.GetNombreModelo());
                return RedirectToAction("Create", new { clienteDni = cliente.dniCliente });
            }
            if (gestionPolizaBLL.ExistMatriculaInPolizasActivas(gestionPoliza.matricula) == true)
            {
                TempData["mensaje"] = ItemMensaje.ErrorValidarMatriculaDuplicada(Poliza.GetNombreModelo(), gestionPoliza.matricula);
                return RedirectToAction("Index");
            }
            // Validaciones de rangos de fecha.
            DateTime today = DateTime.Today;
            if (gestionPoliza.fechaInicio < today)
            {
                TempData["mensaje"] = ItemMensaje.ErrorFechaInicioMenorHoy(Poliza.GetNombreModelo());
                return RedirectToAction("Create", new { clienteDni = cliente.dniCliente });
            }
            if (gestionPoliza.fechaFin > gestionPoliza.fechaInicio.AddYears(1))
            {
                TempData["mensaje"] = ItemMensaje.ErrorFechasMaxRangoInicioFin(Poliza.GetNombreModelo(), 365);
                return RedirectToAction("Create", new { clienteDni = cliente.dniCliente });
            }
            if (gestionPoliza.fechaFin > today.AddYears(1).AddMonths(6))
            {
                TempData["mensaje"] = ItemMensaje.ErrorFechasMaxRangoHoyFin(Poliza.GetNombreModelo(), 547);
                return RedirectToAction("Create", new { clienteDni = cliente.dniCliente });
            }
            try
            {
                var usuario = GetUsuarioLogado();
                Poliza polizaCreada = gestionPolizaBLL.CreatePolizaAndFirstGestionPoliza(gestionPoliza, usuario, cliente);
                TempData["mensaje"] = ItemMensaje.SuccessCrear(Poliza.GetNombreModelo(), polizaCreada.polizaId.ToString(CultureInfo.GetCultureInfo("es-ES")));
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                gestionPolizaBLL.UnCreatePoliza(cliente);

ProyectoSegurosFpDaw/Views/GestionPolizas/Create.cshtml
@model ProyectoSegurosFpDaw.Models.GestionPoliza

@{
    ViewBag.Title = "Crear Póliza";

    var cliente = new ProyectoSegurosFpDaw.Models.Cliente();
}

@section css{
    <!-- Date range Picker -->
    <link href="~/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" />
}

<!-- Header -->
<section class="fixedHeader-locked">
    <div col-sm-3>
        <div class="card card-gray ">
            <div class="card-header">
                <h2 class="card-title">PÓLIZAS</h2>
            </div>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            @using (Html.BeginForm("Create", "GestionPolizas", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                if (ViewBag.cliente != null)
                {
                    cliente = ViewBag.cliente as ProyectoSegurosFpDaw.Models.Cliente;
                    @Html.Hidden("clienteId", cliente.clienteId)
                }
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Crear Póliza</h3>
                        <div class="card-tools">
                        </div>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled form-inline">
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(m => m.Poliza.Cliente.nombreCliente, new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-portrait"></i></span>
                                    </div>
                                    @Html.TextBox("nombreCliente", cliente.nombreCliente, new { @class = "form-control", @autocomplete = "off", @readonly = true })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(m => m.Poliza.Cliente.apellido1Cliente, new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-portrait"></i></span>
                                    </div>
                                    @Html.TextBox("apellido1Cliente", cliente.apellido1Cliente, new { @class = "form-control", @autocomplete = "off", @readonly = true })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(m => m.Poliza.Cliente.apellido2Cliente, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-portrait"></i></span>
                                    </div>
                                    @Html.TextBox("apellido2Cliente", cliente.apellido2Cliente, new { @class = "form-control", @autocomplete = "off", @readonly = true })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(m => m.Poliza.Cliente.dniCliente, new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-id-card"></i></span>
                                    </div>
                                    @Html.TextBox("dniCliente", cliente.dniCliente, new { @class = "form-control", @autocomplete = "off", @readonly = true })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(m => m.Poliza.Cliente.emailCliente, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-at"></i></span>
                                    </div>
                                    @Html.TextBox("emailCliente", cliente.emailCliente, new { @class = "form-control", @autocomplete = "off", @readonly = true })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(m => m.Poliza.Cliente.telefonoCliente, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-mobile-alt"></i></span>
                                    </div>
                                    @Html.TextBox("telefonoCliente", cliente.telefonoCliente, new { @class = "form-control", @autocomplete = "off", @readonly = true })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(model => model.matricula, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-car-alt"></i></span>
                                    </div>
                                    @Html.EditorFor(model => model.matricula, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @maxlength = "10" } })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(model => model.marcaVehiculo, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-car"></i></span>
                                    </div>
                                    @Html.EditorFor(model => model.marcaVehiculo, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @maxlength = "20" } })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(model => model.modeloVehiculo, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-car"></i></span>
                                    </div>
                                    @Html.EditorFor(model => model.modeloVehiculo, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @maxlength = "20" } })
                                </div>
                            </li>
                            <li class=" col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.Label("Inicio / Fin de Póliza", htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fas fa-calendar-plus"></i>
                                        </span>
                                    </div>
                                    @Html.TextBox("fechaApertura", null, new { @class = "form-control float-right", @autocomplete = "off" })
                                    @Html.Hidden("fechaInicio")
                                    @Html.Hidden("fechaFin")
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(m => m.CondicionadoPoliza.tipoCondicionado, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-list-ol"></i></span>
                                    </div>
                                    @Html.DropDownList("condicionadoPolizaId", null, htmlAttributes: new { @class = "form-control" })
                                </div>
                            </li>
                            <li class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(model => model.observaciones, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-comment-dots"></i></span>
                                    </div>
                                    @Html.EditorFor(model => model.observaciones, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @rows = 1, @maxlength = "500" } })
                                </div>
                            </li>
                            <li class="ccol-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-3">
                                @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label" })
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-euro-sign"></i></span>
                                    </div>
                                    @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                </div>
                            </li>
                            @*  ----------------------------------------------------------------------------------------------*@
                            <li class=" col-xs-12  col-md-12 mb-4">

                            </li>
                            @*  ----------------------------------------------------------------------------------------------*@
                        </ul>
                        <div class="row">
                            <div class="col-2 col-sm-1 row">
                                <a href="@Url.Action("Index","GestionPolizas")" class="btn btn-info float-left">
                                    <i class="fas fa-reply"> </i>
                                </a>
                            </div>
                            <div class="col row justify-content-end">
                                <a href="@Url.Action("Edit", "Clientes", new { id = cliente.clienteId })" class="btn btn-info mr-2 ">
                                    <i class="fas fa-edit"> </i>
                                    Editar Cliente
                                </a>
                                <button type="submit" class="btn btn-info float-right">
                                    <i class="fas fa-plus-square"> </i>
                                    Crear Póliza
                                </button>
                            </div>
                        </div>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            }
        </div>
    </div>
</section>
<!-- /.content -->

@section Scripts{
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <script src="~/Scripts/SharedScripts.js"></script>
    <script src="~/Scripts/GestionPolizasSharedScripts.js"></script>
    <script src="~/Scripts/GestionPolizasCreateScript.js"></script>
}

ProyectoSegurosFpDaw/Views/GestionPolizas/Historico.cshtml
@model ProyectoSegurosFpDaw.Models.GestionPoliza

@{
    ViewBag.Title = "Histórico Póliza";
}

@section css{
    <!-- Datatables -->
    <link href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <!-- Date range Picker -->
    <link href="~/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" />
}

<!-- Header -->
<section class="fixedHeader-locked">
    <div col-sm-3>
        <div class="card card-gray ">
            <div class="card-header">
                <h2 class="card-title">PÓLIZAS</h2>
            </div>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Historial de Gestiones. Póliza Id : <b>@ViewBag.polizaId </b> </h3>
                    <div class="card-tools">
                    </div>
                </div>
                <div class="card-body">
                    <table id="tableResultados" class="table table-bordered table-hover " style="width:100%">
                        <thead class="thead-light">
                            <tr>
                                <th>@Html.LabelFor(model => model.gestionPolizaId)</th>
                                <th>@Html.LabelFor(model => model.fechaGestion)</th>
                                <th>@Html.LabelFor(model => model.TipoGestion.nombreGestion)</th>
                                <th>@Html.LabelFor(model => model.Usuario.emailUsuario)</th>
                                <th>@Html.LabelFor(model => model.matricula)</th>
                                <th>@Html.LabelFor(model => model.marcaVehiculo)</th>
                                <th>@Html.LabelFor(model => model.fechaInicio)</th>
                                <th>@Html.LabelFor(model => model.CondicionadoPoliza.tipoCondicionado)</th>
                                <th>@Html.LabelFor(model => model.precio)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ if (ViewBag.historicoLista != null)
                                {
                                    var listaGestiones = ViewBag.historicoLista as IList<ProyectoSegurosFpDaw.Models.GestionPoliza>;
                                    foreach (var item in listaGestiones)
                                    {
                                        <tr>
                                            <td>@item.gestionPolizaId</td>
                                            <td>@item.fechaGestion</td>
                                            <td>@item.TipoGestion.nombreGestion</td>
                                            <td>@item.Usuario.emailUsuario</td>
                                            <td>@item.matricula</td>
                                            <td>@item.marcaVehiculo @item.modeloVehiculo</td>
                                            <td>@item.fechaInicio.ToShortDateString() - @item.fechaFin.ToShortDateString()</td>
                                            <td>@item.CondicionadoPoliza.tipoCondicionado</td>
                                            <td>@item.precio</td>
                                            <td>@item.observaciones </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td>No hay datos coincidentes</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                    <div class="row mt-4">
                        <div class="col-6 col-sm-6 col-md-6">
                            <a href="@Url.Action("Details","GestionPolizas", new { id = ViewBag.gestionPolizaIdLast  })" class="btn btn-info float-left">
                                <i class="fas fa-reply"> </i>
                            </a>
                        </div>
                        <div class="col-6 col-sm-6 col-md-6">
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</section>
<!-- /.content -->

@section Scripts{
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/GestionPolizasHistoricoScript.js"></script>

}